name: addiction-tracker
base: core22
version: '0.0.7'
summary: An app to help with your addiction # 79 char long summary
description: |
  Addiction tracker helps you to stop your addiction by giving you more consciousness over how you 
  use substances and the triggers and emotions related to the use.

grade: stable
confinement: strict

layout:
  /usr/libexec/webkit2gtk-4.1:
    symlink: $SNAP/usr/libexec/webkit2gtk-4.1
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1
  /usr/lib/aarch64-linux-gnu/webkit2gtk-4.1:
    symlink: $SNAP/usr/lib/aarch64-linux-gnu/webkit2gtk-4.1
  /usr/lib/webkit2gtk-4.1/injected-bundle:
    symlink: $SNAP/usr/lib/webkit2gtk-4.1/injected-bundle

apps:
  addiction-tracker:
    command: usr/bin/addiction-tracker
    desktop: usr/share/applications/addiction-tracker.desktop
    plugs:
      - wayland
      - X11

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - libglu1-mesa
      - freeglut3
    source: .
    override-build: |
      set -eu
      rustup default stable
      npm install
      npm run tauri build -- --bundles deb
      dpkg -x src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=addiction-tracker|Icon=/usr/share/icons/hicolor/32x32/apps/addiction-tracker.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/addiction-tracker.desktop
