name: addiction-tracker
base: core22
version: '0.0.4'
summary: An app to help with your addiction # 79 char long summary
description: |
  Addiction tracker helps you to stop your addiction by giving you more consciousness over how you 
  use substances and the triggers and emotions related to the use.

grade: stable
confinement: strict

apps:
  addiction-tracker:
    command: bin/addiction-tracker
    desktop: usr/share/applications/addiction-tracker.desktop

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  prep:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libglu1-mesa
      - libsoup-3.0-0
      - freeglut3
    source: .
    override-pull: |
      set -eu
      craftctl default
      rustup default nightly
      npm install
      npm run tauri build -- --bundles deb
      dpkg -x src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/*.deb here
      sed -i -e "s|Icon=addiction-tracker|Icon=/usr/share/icons/hicolor/32x32/apps/addiction-tracker.png|g" here/usr/share/applications/addiction-tracker.desktop
      cp -r here/* .
    organize:
      usr/bin/addiction-tracker: bin/addiction-tracker
